---
title: "Untitled"
author: "RN7"
date: "June 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(ggthemes)
library(ggrepel)
library(grid)

worldcup_raw <- 
  read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/week11_fifa_audience.csv") %>% 
  select(-X1) 

worldcup_confed_sum <- worldcup_raw %>% 
  add_count(country) %>% 
  group_by(confederation) %>% 
  summarize_if(is.numeric, sum) %>% 
  ungroup() %>% 
  mutate(total_members = sum(n),
         perc_members = (n / total_members) * 100,
         perc_members = perc_members %>% round(1)) %>% 
  select(-n, -total_members) %>% 
  gather(key = share_var, value = value, -confederation)

# re-order variables as factors for the plot
worldcup_confed_sum <- worldcup_confed_sum %>% 
  mutate(share_var = share_var %>% as_factor(),
         share_var = share_var %>% fct_relevel("perc_members", "population_share",
                                               "tv_audience_share", "gdp_weighted_share"))
# re-order confederations
worldcup_confed_sum <- worldcup_confed_sum %>% 
  mutate(confederation = confederation %>% as_factor(),
         confederation = confederation %>% fct_relevel("OFC", "CAF", "CONMEBOL", 
                                                       "CONCACAF", "AFC", "UEFA"))
# have % label ONLY for UEFA
worldcup_confed_sum <- worldcup_confed_sum %>% 
  mutate(val2 = if_else(confederation == "UEFA", paste0(value, "%"), paste0(value)))

perc_labs <- c("FIFA MEMBERS", "GLOBAL \nPOPULATION",
               "WORLD CUP TV \nAUDIENCE", "GDP-WEIGHTED \nTV AUDIENCE")

confed_labs <- c("OFC (Oceania)", "CAF (Africa)", "CONMEBOL (S. America)",
                 "CONCACAF (N. America)", "AFC (Asia)", "UEFA (Europe)")

```

FiveThirtyEight Heatmap:

```{r fig.height=6, fig.width=10}

# Different greens: #00CD00 #008B00 #e5f5e0 #31a354)
p <- 
  ggplot(worldcup_confed_sum,
         aes(share_var, confederation, 
             fill = value)) +
  geom_tile(color = "lightgrey") +
  scale_fill_gradient(low = "#e5f5e0", high = "#008B00") + #  mid = "#a1d99b"
  geom_text(aes(label = val2, fontface = "bold"), size = 5) +
  theme_fivethirtyeight() +                   # erases axis.title, text font not the actual one?
  theme(legend.position = "none",
        text = element_text(face = "bold", color = "black"),
        axis.title = element_text(),          # to add axis.title back into plot...
        axis.title.x.top = element_text(margin = margin(b = 10)),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(hjust = 0, size = 12),
        plot.margin = rep(grid::unit(0.75, "cm"), 4)
        ) +
  scale_x_discrete(position = "top", expand = c(0, 0),
                   labels = perc_labs) +
  labs(x = "IN 2010, SHARE OF ...", y = "") + 
  scale_y_discrete(expand = c(0, 0),
                   labels = confed_labs) +
  annotation_custom(grob = textGrob(
    label = expression(bold("CONFEDERATION")), # use bold() inside expression() to get BOLD text
    gp = gpar(cex = 1.0, fontface = "bold", hjust = 0)), # also need to specify in fontface as well
                    ymin = 6.66, ymax = 6.66,
                    xmin = -0.23, xmax = -0.23) +     
  annotation_custom(grob = linesGrob(), 
                    xmin = 0.5, xmax = 4.5, ymin = 7, ymax = 7) + # top bar
  annotation_custom(grob = linesGrob(gp = gpar(lwd = 3)),  
                    xmin = -0.64, xmax = 4.5, ymin = 6.5, ymax = 6.5) # x-axis bar

pt <- ggplot_gtable(ggplot_build(p))
pt$layout$clip[pt$layout$name == "panel"] <- "off"  # so stuff outside the plot can be shown.

grid.newpage()
grid.draw(pt) # doesn't show anything...?

plot(pt) # use plot instead i guess...

#g <- plot(pt) 

# took a gabillion times to get the positioning of the grobs just right but ... worth it? eh.

#ggsave(file = "recreated_538_heatmap.png", plot(pt))

#g_g <- save(pt, file = "grobby.png")

```




```{r}

glimpse(worldcup_raw)

glimpse(worldcup_confed_sum)


worldcup_raw %>% arrange(desc(tv_audience_share))


library(rvest)
library(janitor)

url <- "https://en.wikipedia.org/wiki/2010_FIFA_World_Cup"

wc_2010_raw <- url %>% 
  read_html() %>% 
  html_nodes(".mw-parser-output > div:nth-child(29) > table:nth-child(1)") %>% 
  html_text()

# .mw-parser-output > div:nth-child(29) > table:nth-child(1)

wc_2010_raw %>% 
  str_remove_all("\n") %>% 
  str_remove_all("\\([^()]+\\)") %>% # get rid of () and those with contents therein
  str_remove_all("[A-Z]{3,}") %>%    # get rid of confed names (All Caps longer than 3)
  str_replace("North Korea", "North_Korea") %>% 
  str_replace("South Korea", "South_Korea") %>% 
  str_replace("United States", "United_States") %>% 
  str_replace("Ivory Coast", "Ivory_Coast") %>% 
  str_replace("New Zealand", "New_Zealand") %>% 
  str_replace("South Africa", "South_Africa") %>% 
  str_trim()
  str_replace("\\s+", " ") %>% 
  str_split(" ")

wc_2010_tab <- "https://en.wikipedia.org/wiki/2010_FIFA_World_Cup_qualification" %>% 
  read_html() %>% 
  html_nodes("table.wikitable:nth-child(13)") %>% 
  html_table()

wc_2010_tab <- wc_2010_tab %>% flatten_df()

class(wc_2010_tab)
glimpse(wc_2010_tab)


```



```{r}
library(ggrepel)

wc_2010_teams <- wc_2010_tab %>% pull(Team)

worldcup_raw %>% 
  mutate(wc_2010 = if_else(country %in% wc_2010_teams, T, F)) %>% 
  ggplot(aes(x = population_share/100, 
           y = tv_audience_share/100)) +
  geom_point(aes(size = gdp_weighted_share/100, 
                 color = confederation)) +
  scale_x_sqrt(labels = scales::percent) +
  scale_y_sqrt(labels = scales::percent) 



```




```{r}
# from FIFA Big Count (2006):
# % of population that are involved in football (m/f players, referees, officials).
players_perc <- c(2.22, 5.16, 8.53, 7.47, 4.68, 7.59)




worldcup_raw %>% 
  add_count(country) %>% 
  group_by(confederation) %>% 
  summarize_if(is.numeric, sum) %>% 
  ungroup() %>% 
  mutate(total_members = sum(n),
         perc_members = (n / total_members) * 100,
         perc_members = perc_members %>% round(1)) %>% 
  select(-n, -total_members) %>% 
  mutate(players_share = players_perc) %>% 
  ggplot(aes(x = players_perc / 100, 
             y = tv_audience_share / 100)) +
  geom_point(aes(size = population_share)) +
  geom_label(aes(label = confederation), nudge_x = 0.02, nudge_y = 0.02) +
  scale_y_sqrt(labels = scales::percent,
               expand = c(0, 0),
               limits = c(0, 0.5),
               breaks = c(0.1, 0.2, 0.3, 0.4, 0.5)) +
  scale_x_sqrt(labels = scales::percent, 
               expand = c(0, 0),
               limits = c(0, 0.12),
               breaks = c(0.02, 0.04, 0.06, 0.08, 0.1)) +
  annotate("text", x = 0.01, y = 0.05, 
           label = "AFC is clear outlier,\nmost likely due to India & China") +
  theme_solarized() +
  labs(caption = "Player data from 2007...")


```





```{r}
worldcup_raw %>% 
  add_count(country) %>% 
  group_by(confederation) %>% 
  summarize_if(is.numeric, sum) %>% 
  ungroup() %>% 
  mutate(total_members = sum(n),
         perc_members = (n / total_members) * 100,
         perc_members = perc_members %>% round(1)) %>% 
  select(-n, -total_members) %>% 
  mutate(players_share = players_perc) %>% 
  ggplot(aes(x = players_perc / 100, 
             y = (tv_audience_share / 100) / (population_share / 100))) +
  geom_point(aes(size = population_share)) +
  geom_label(aes(label = confederation), nudge_x = 0.01, nudge_y = 0.01)


```



```{r}
library(tidyverse)
library(ggthemes)
library(ggrepel)
library(grid)

# Calculate football player share (Registered/Unregistered)

# registered + unregistered, IN 1000s
total_players <- (38287 + 226265) * 1000

afc <- 4040 + 81136

caf <- 3101 + 43199

concacaf <- 6121 + 36988

conmebol <- 3759 + 24018

ofc <- 241 + 301

uefa <- 21025 + 40622

players <- c(afc, caf, concacaf, conmebol, ofc, uefa) * 1000

# 2007 pop

pop_2007 <- c(3870439, 909575, 518613, 374235, 12252, 844677) * 1000


worldcup_confed <- worldcup_raw %>% 
  add_count(country) %>% 
  group_by(confederation) %>% 
  summarize_if(is.numeric, sum) %>% 
  ungroup() %>% 
  mutate(total_members = sum(n),
         perc_members = (n / total_members) * 100,
         perc_members = perc_members %>% round(1)) %>% 
  select(-n, -total_members)

worldcup_confed <- worldcup_confed %>% 
  mutate(players = players,
         total_pop = pop_2007,
         total_players = total_players,
         players_per_pop_1000 = (players / total_pop) * 1000, # player per capita (1000 people)
         players_share = players_per_pop_1000 / sum(players_per_pop_1000) * 100)  %>% 
  mutate(image = "https://d30y9cdsu7xlg0.cloudfront.net/png/2034-200.png")

# plot

worldcup_confed %>% 
  ggplot(aes(x = players_share / 100, 
             y = tv_audience_share / 100)) +
  geom_point(aes(size = players_per_pop_1000)) +
  geom_label_repel(aes(label = confederation), nudge_x = 0.02, nudge_y = 0.05) +
  scale_y_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks()
               
               ) +
  scale_x_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks()
               ) +
  theme_solarized() +
  theme(legend.position = "none") +
  labs(x = "Share of Players per Capita \n (1 Player per 1000 people)",
       y = "Share of TV Audience",
       caption = "Source: FiveThirtyEight.com")

# players per pop

```

```{r}
worldcup_confed %>% 
  ggplot(aes(x = players_share / 100, 
             y = tv_audience_share / 100)) +
  geom_point(aes(size = players_per_pop_1000)) +
  geom_label(aes(label = confederation), nudge_x = 0.02, nudge_y = 0.05) +
  scale_y_continuous(labels = scales::percent,
               breaks = scales::pretty_breaks()
               
               ) +
  scale_x_continuous(labels = scales::percent,
               breaks = scales::pretty_breaks(),
               expand = c(0, 0)
               ) +
  theme_solarized() +
  theme(legend.position = "none") +
  labs(x = "Share of Players per Capita (1000 people)",
       y = "Share of TV Audience",
       caption = "Source: FiveThirtyEight.com")



library(ggimage)
library(extrafont)
library(hrbrthemes)
loadfonts()

# there is a better way to do this with case_when() but whatever it's 3AM.
confed_labs <- c("AFC (Asia)", "CAF (Africa)", "CONCACAF (N. America)",
                 NA, NA , NA)

confed_labs2 <- c(NA, NA , NA,
                  "CONMEBOL (S. America)", "OFC (Oceania)", "UEFA (Europe)")

worldcup_confed %>% 
  ggplot(aes(x = players_share / 100, 
             y = tv_audience_share / 100)) +
  geom_image(aes(image = image), size = 0.05) +
  geom_label_repel(aes(label = confed_labs), 
                   family = "Roboto Condensed",
                   nudge_x = 0.02, nudge_y = -0.05,
                   force = 20) +
  geom_label_repel(aes(label = confed_labs2), 
                   family = "Roboto Condensed",
                   nudge_x = 0.02, nudge_y = 0.045,
                   force = 20) +
  scale_y_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks(5)
               
               ) +
  scale_x_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks(5),
               limits = c(NA, 0.27)) +
  theme_ipsum() +
  theme(
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "",
    subtitle = "Players = Unregistered & Registered, Male & Female",
    x = "Share of Players per Capita \n (1 Player per 1000 people)",
    y = "Share of TV Audience",
    caption = "Source: FiveThirtyEight.com") +
  annotate("text", x = 0.085, y = 0.1, 
           label = "AFC is the clear outlier,\nmost likely due to India & China",
           family = "Roboto Condensed")

```


```{r fig.height=6, fig.width=8}

worldcup_confed2 <- worldcup_confed %>% 
  mutate(image = "https://d30y9cdsu7xlg0.cloudfront.net/png/43563-200.png")

# 1 "http://extras.mnginteractive.com/live/media/site27/2017/0928/20170928_093500_Soccer%20ball.png"
# 2 "https://d30y9cdsu7xlg0.cloudfront.net/png/43563-200.png"

worldcup_confed2 %>% 
  ggplot(aes(x = players_share / 100, 
             y = tv_audience_share / 100)) +
  geom_image(aes(image = image), size = 0.06) +
  geom_label_repel(aes(label = confed_labs), 
                   family = "Trebuchet MS",
                   nudge_x = 0.02, nudge_y = -0.06,
                   force = 20) +
  geom_label_repel(aes(label = confed_labs2), 
                   family = "Trebuchet MS",
                   nudge_x = 0.03, nudge_y = 0.07,
                   force = 20) +
  scale_y_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks(5),
               limits = c(NA, 0.5)
               ) +
  scale_x_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks(5),
               limits = c(NA, 0.27)) +
  theme_minimal() +
  theme(
    text = element_text(family = "Trebuchet MS", color = "black"),
    panel.grid.minor = element_blank(),
    plot.subtitle = element_text(size = 8, family = "Arial Narrow"),
    axis.text = element_text(size = 12)
  ) +
  labs(
    title = "Share of Players per Capita & TV Audience (2010 World Cup)\nby Football Confederations",
    subtitle = "Players: Total of Unregistered & Registered, Male & Female",
    x = "Share of Players per Capita \n (1 Player per 1000 people)",
    y = "Share of TV Audience",
    caption = "Source: FiveThirtyEight.com & FIFA Big Count (2006)") +
  annotate("text", x = 0.088, y = 0.15, 
           label = "AFC (Asia) is the clear outlier,\nmost likely due to India & China",
           family = "Trebuchet MS", fontface = "bold")

```








```{r fig.height=6, fig.width=8}
library(tidyverse)
library(ggthemes)
library(ggrepel)
library(ggimage)
library(extrafont)
# loadfonts()

worldcup_raw <- 
  read_csv(
    "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/week11_fifa_audience.csv") %>% 
  select(-X1) 

# Calculate football player share (Registered/Unregistered, Male/Female)
# data from FIFA Big Count (2006)

# registered + unregistered, male + female IN 1000s
total_players <- (38287 + 226265) * 1000

afc <- 4040 + 81136

caf <- 3101 + 43199

concacaf <- 6121 + 36988

conmebol <- 3759 + 24018

ofc <- 241 + 301

uefa <- 21025 + 40622

# as one vector in ordnung
players <- c(afc, caf, concacaf, conmebol, ofc, uefa) * 1000

# 2006 pop, also in 1000s
pop_2006 <- c(3870439, 909575, 518613, 374235, 12252, 844677) * 1000

# new dataframe
worldcup_confed <- worldcup_raw %>% 
  add_count(country) %>% 
  group_by(confederation) %>% 
  summarize_if(is.numeric, sum) %>% 
  ungroup() %>% 
  mutate(players = players,
         total_pop = pop_2006,
         total_players = total_players,
         players_per_pop_1000 = (players / total_pop) * 1000, # player per capita (1000 people)
         players_share = players_per_pop_1000 / sum(players_per_pop_1000) * 100) 

# add soccer ball image
worldcup_confed <- worldcup_confed %>% 
  mutate(image = "https://d30y9cdsu7xlg0.cloudfront.net/png/43563-200.png")

# there is a better way to do this with case_when() but whatever it's 3AM.
confed_labs <- c("AFC (Asia)", "CAF (Africa)", "CONCACAF (N. America)",
                 NA, NA , NA)

confed_labs2 <- c(NA, NA , NA,
                  "CONMEBOL (S. America)", "OFC (Oceania)", "UEFA (Europe)")

# PLOT
p <- worldcup_confed %>% 
  ggplot(aes(x = players_share / 100, 
             y = tv_audience_share / 100)) +
  geom_image(aes(image = image), size = 0.06) +
  geom_label_repel(aes(label = confed_labs), 
                   family = "Trebuchet MS",
                   nudge_x = 0.02, nudge_y = -0.06,
                   force = 20) +
  geom_label_repel(aes(label = confed_labs2), 
                   family = "Trebuchet MS",
                   nudge_x = 0.03, nudge_y = 0.07,
                   force = 20) +
  scale_y_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks(5),
               limits = c(NA, 0.5)
               ) +
  scale_x_sqrt(labels = scales::percent,
               breaks = scales::pretty_breaks(5),
               limits = c(NA, 0.27)) +
  theme_minimal() +
  theme(
    text = element_text(family = "Trebuchet MS", color = "black"),
    panel.grid.minor = element_blank(),
    plot.subtitle = element_text(size = 8, family = "Arial Narrow"),
    axis.text = element_text(size = 12)
  ) +
  labs(
    title = "Share of Players per Capita & TV Audience (2010 World Cup)\nby Football Confederations",
    subtitle = "Players: Total of Unregistered & Registered, Male & Female",
    x = "Share of Players per Capita \n (1 Player per 1000 people)",
    y = "Share of TV Audience",
    caption = "Source: FiveThirtyEight.com & FIFA Big Count (2006)") +
  annotate("text", x = 0.088, y = 0.15, 
           label = "AFC (Asia) is the clear outlier,\nmost likely due to India & China",
           family = "Trebuchet MS", fontface = "bold")

ggsave(p, filename = "worldcup_tv_player.png")

```









